int advance(char *lp, char *ep);
int append(int (*f)(void), unsigned int *a);
int cclass(char *set, int c, int af);
void error(char *s);
void exfile(void);
void filename(const char* c);
char *getblock(unsigned int atl, int iof);
int getchr(void);
int getfile(void);
void init(void);
void newline(void);
void nonzero(void);
void print(void);
void putchr_(int ac);
void putd(void);
void putfile(void);
int putline(void);
void puts_(char *sp);
void readfile(const char* c);
void search(const char* re);
void setwide(void);
void squeeze(int);
