long	lseek(int, long, int);
int	close(int);

char	*mktemp(char *);
char	tmpXXXXX[50] = "/tmp/eXXXXX";

char *getblock(unsigned int atl, int iof);
char *getline_(unsigned int tl);
unsigned int* address(void);
int advance(char *lp, char *ep);
int append(int (*f)(void), unsigned int *a);
int cclass(char *set, int c, int af);
void compile(int eof);
void error(char *s);
int execute(unsigned int *addr);
void exfile(void);
void filename(const char* c);
int getchr(void);
int getfile(void);
void global(int k);
void init(void);
void nonzero(void);
void print(void);
void putchr(int ac);
void putd(void);
int putline(void);
void quit(int n);
void readfile(const char* fn);
void search(const char* re);
void setwide(void);
void squeeze(int i);
void ungetch_(int c);